---
title: "Pakistan Poliovirus Population Immunity"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(rgeos)
library(maptools)
library(ggplot2)
library(mapproj)
source("C:/Files/Polio/Pakistan/Scripts/PAK_SIAD_Data_Prep.R")
source("C:/Files/Polio/Pakistan/Scripts/PAK_Function_plotggMap.R")


```

####This page is a example of an R Markdown page, using Pakistan Poliovirus Population Immunity as an example.


Immunity trends since 2001
```{r}
temp = aggregate(preds[3], preds[1], mean)
ggplot(temp, aes(x=year, y=type1_immunity)) + geom_line() + geom_point() + labs(y="Mean Type 1 Immunity",x="Six-Month Interval") + scale_y_continuous(limit=c(0,1))
```

Histogram of immunity estimates from 2014
```{r}
hist(preds$type1_immunity[preds$year==2014], main="District Type 1 Immunity in 2014", xlab="Estimated Type 1 Immunity", ylab="District Count")
```

Map of District Type 1 Immunity

```{r, echo=T, out.width = 800, out.height = 950}
plt <- plotggMap(data=preds[preds$year==2014,], var.name="type1_immunity",id.var.name="index", brewer.cols=brewer.pal(9,"RdYlGn"), na.col="grey50", 
             legend.title="Type 1\nImmunity", main.title="Esimated Type 1 Immunity", map=district, var.limits=c(0,1), breaks=seq(0,1,.2), legend.pos=NA) #c(.93,.35)
plt 
```

